### ISSUE TITLE
A question really, not an issue

### ISSUE THREAD

**Issue by kcrca** [burnnat/capitals#4]
No way to "send message to repository owner" (afaik) so ...

I'm trying to do an add-on that looks much like yours, but works with punctuation correction, not capitalization. In other words, I need the same structure, but different guts. Your add-on seems very clean and smooth, so I thought I'd start here, I hope that's OK. (If you're interested I'd be happy even to add it in to yours, but it seems different enough to seem odd to do so.)

One thing I can't find documented is how you go from a source repository to an installed add-on for development. Do I upload each file separately, and then reupload (via paste) when I change a file? Is there a smoother way to do this? Advice would be welcome.

**Comment by burnnat** [comment]
Unfortunately, there's no better method than copy-paste that I'm aware of. For standalone Google Apps Script projects, you can upload programmatically using [Google Drive SDK](https://developers.google.com/apps-script/import-export) in conjunction with something like [gdcmdtools](https://github.com/timchen86/gdcmdtools), but unfortunately container-bound scripts (like Google Docs addons) are not accessible through the API so that approach won't work.

It is theoretically possible to import standalone Google Apps scripts as libraries into your addon, so that the bulk of the code could be updated automatically, leaving only a thin wrapper in the addon itself. But this comes at a performance cost and Google's documentation on [libraries](https://developers.google.com/apps-script/guide_libraries) explicitly advises against it:

> **Warning:** A script that uses a library will not run as quickly as it would if all the code were contained within a single script project. Although libraries can make development and maintenance more convenient, you should avoid them in projects where speed is critical. Because of this issue, libraries should not be used in add-ons.

So in the end, I'm still stuck using manual copy-paste, much to my chagrin... :cry:

**Comment by kcrca** [comment]
Ah well, that’s about what I expected, as opposed to what I hoped…

About the library issue, I saw that as well, it’s funny that they have a non-trivial support system for it and yet recommend against it. 

In any case, your app is factored to make the transformations separate from manipulating the text, and with a little reorganization I think could easily be made a “library” in a “.gs files you can copy” kind of way. At least then you and I could share that part back and forth if we fix bugs with it or whatever. I’ll take a whack at it, and if I think I figure out something that would actually work that way I’ll offer it to you as a fork.

		Ken Arnold
		健

**Comment by burnnat** [comment]
Sounds good... Looking forward to seeing what you come up with!

**Comment by kcrca** [comment]
Well, first I have to get anything working. I’ve uploaded capitals as my own app under my own name (otherwise unchanged) and tried to run it using Publish > Test as add-on. The add-on menu looks right, but when I select anything from it I get an error: Cannot read property 'C' of undefined. Of course C is a mangled name, as are all the symbols on the stack, so that’s not so helpful. Running the installed Capitals add-on works just fine. If you happen to have a clue…

		Ken
		健

P.S. If you’d prefer to take this to personal email, I’m arnold at the domain peak.im (man, I hate avoiding bots…)
